---
title: Characterizing the relationship between pain and opioid relapse in adults with opioid use disorder
author:
  - name: Kendra Wyant 
    affiliations:
      - Department of Psychology, University of Wisconsin-Madison
bibliography: references.bib
number-sections: false 
editor_options: 
  chunk_output_type: console
---

## Background

Opioid use disorder is a chronic relapsing disease. There is an extant relapse prevention literature that characterizes the chronic non-linear nature of lapse, relapse, and recovery. The relapse prevention model suggests that "relapse is a fluctuating process that begins prior to and extends beyond the return to target behavior". It also posits that lapses are preceded by a high-risk situation (e.g., emotional or cognitive states, environmental contingencies, physiological states) that, if recognized, could be targeted with intervention. Importantly, high-risk situations differ between individuals and within an individual over-time. As such, identifying imminent risk of relapse is complex.

Pain is a widely cited risk factor for opioid relapse. Individuals with opioid used disorder often mention this as being a top reason for relapse or escalation of use. However, the relationship between pain and relapse is complex.   

For example, one study found that past week pain was significantly associated with increased craving, but there were no significant relationship between pain and positive urine analysis for opioids[@tsuiChronicPainCraving2016]. Other studies, have found higher pain severity to be related to opioid use in individuals not engaged in treatment or pursuing abstinence[@LongitudinalAssociationPain]. For individuals engaged in treatment, pain alone has not been consistently shown to be predictive of relapse[@nwaefunaAssessingRelapsePatients2024; @najiProspectiveStudyInvestigate2016; @macleanImpactChronicPain2021].

One reason, for the mixed findings may be due to the heterogeneous and multidimensional nature of relapse. Risk and protective factors, as well as characteristics of the individual, may all interact to influence the relationship between pain and opioid relapse. 

## Present Study
The present study proposes to look at the relationship of past month pain and percentage of days of opioid use in the next month in a sample of individuals in early recovery from opioid use disorder and with a goal of abstinence.   

It will also look at the moderating effects of potential protective factors (social support, medication treatment adherence, and self-efficacy) and individual characteristics (traits, socioeconomic status, age, race and ethnicity), on the relationship between pain and percent days of opioid use in the next month.

## Dataset

Data comes from a longitudinal (up to twelve months) study with a national sample of adults with opioid use disorder.   

### Baseline Measures Collected at Intake

1. Demographics: Age, race, education, income, employment, and relationship status.    

2. Pain Catastrophizing Scale: A 3-item scale that measures the extent to which individuals magnify the threat value of pain stimuli, ruminate, and feel helpless in the presence of pain.   

3. Distress Tolerance Scale: A 15-item scale that measures the ability to withstand negative emotional states.

### Monthly Measures Collected at Intake and Each Month on Study

1. Brief Pain Inventory: A 4-item scale that measures pain severity, interference, and planned pain treatment services.   

2. Social Connectedness Scale: A 6-item scale that measures the extent to which individuals feel connected to and supported by others.

3. Perceived Stress Scale: A 4-item scale that measures the extent to which individuals perceive their lives as unpredictable, uncontrollable, and overwhelming.

4. Treatment Adherence: Frequency, effectiveness, and likelihood of continuing medications and treatments for opioid use disorder.

5. Abstinence Self-efficacy: 3 questions about satisfaction, confidence, and motivation to abstain from opioids.   


### Outcome Measure

Percentage of days of opioid use is measured using daily diaries. Each day on study, participants were asked to report any opioid use they had not yet reported. They then selected the date and time of their opioid use. 

## Significance

Understanding relapse risk can help clinicians select the best interventions for relapse prevention. Additionally, understanding the relationship between pain, additional factors, and relapse can help treatment providers tailor strategies for managing pain in individuals with opioid use disorder. 


## References

::: {#refs}
:::



